language: python
python:
  - '3.6'

#
# Command to install dependencies.
#
install:
  - ls -l pcodes/*json
  - pip install codecov
  - pip install -r test-requirements.txt

#
# Run tests + coverage.
#
before_script: py.test --cov-config .coveragerc --cov-report= --cov=.

#
# Send coverage report to coveralls.io and run main script
#
script:
  - codecov
  - cd run
  - python3 schemacreator.py

#
# Deploy dev branch to prod
#
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
#  local-dir: recipes
  keep-history: true
  verbose: true
  target-branch: prod
  on:
    branch:
      - dev

