dist: trusty
language: python
python:
- '3.6'
install:
- ls -l pcodes/*json
- pip install -r requirements.txt
script:
- cd run
- python3 schemacreator.py
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
#  local-dir: recipes
  keep-history: true
  verbose: true
  target-branch: dev
  on:
    branch:
      - master
      - dev

